spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.140:3306/shiro-web
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.10.140
    port: 6379
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

shiro:
  loginUrl: /login.html
  unauthorizedUrl: /401.html  # 针对过滤器链生效，针对注解不生效

server:
  port: 8081
